services:
  app:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    image: 'nobe-app:latest'
    restart: "no"
    stdin_open: true
    tty: true
    environment:
      APP_ENV: production
      APP_DEBUG: 'false'
    depends_on:
      pgsql:
        condition: service_healthy

  pgsql:
    build:
      context: ./docker/pgsql
      dockerfile: Dockerfile
    image: 'custom-postgres-repack:17'
    command: ['postgres', '-c', 'max_locks_per_transaction=1024']
    restart: unless-stopped
    environment:
      POSTGRES_DB: '${DB_DATABASE:-nobe}'
      POSTGRES_USER: '${DB_USERNAME:-nobe}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
    volumes:
      - 'nobe-pgsql-data:/var/lib/postgresql/data'
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', '${DB_DATABASE:-nobe}', '-U', '${DB_USERNAME:-nobe}']
      retries: 3
      timeout: 5s

volumes:
  nobe-pgsql-data:
    driver: local
