services:
  laravel.test:
    build:
      context: ./docker/8.5
      dockerfile: Dockerfile
      args:
        WWWGROUP: '1000'
    image: 'nobe-app:latest'
    restart: unless-stopped
    environment:
      WWWUSER: '1000'
      LARAVEL_SAIL: 1
      APP_ENV: production
      APP_DEBUG: 'false'
      XDEBUG_MODE: 'off'
    volumes:
      - '.:/var/www/html'
    depends_on:
      pgsql:
        condition: service_healthy
    labels:
      - "coolify.managed=true"

  pgsql:
    build:
      context: ./docker/pgsql
      dockerfile: Dockerfile
    image: 'custom-postgres-repack:17'
    command: ['postgres', '-c', 'max_locks_per_transaction=1024']
    restart: unless-stopped
    environment:
      POSTGRES_DB: '${DB_DATABASE:-nobe}'
      POSTGRES_USER: '${DB_USERNAME:-sail}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
    volumes:
      - 'nobe-pgsql-data:/var/lib/postgresql/data'
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', '${DB_DATABASE:-nobe}', '-U', '${DB_USERNAME:-sail}']
      retries: 3
      timeout: 5s

volumes:
  nobe-pgsql-data:
    driver: local
